# Generated by Django 5.0.1 on 2025-12-09 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("company", models.CharField(blank=True, max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("lost", "Lost"),
                        ],
                        default="lead",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Where this contact came from",
                        max_length=100,
                    ),
                ),
                ("next_follow_up_at", models.DateTimeField(blank=True, null=True)),
                ("last_contacted_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "email"], name="contacts_co_owner_i_d0f936_idx"
                    )
                ],
            },
        ),
    ]
