# Generated by Django 5.0.1 on 2025-12-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="contact_cadence",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("annual", "Annual"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_pref",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("sms", "SMS"),
                    ("none", "None"),
                ],
                default="email",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_type",
            field=models.CharField(
                choices=[("contact", "Contact"), ("company", "Company")],
                default="contact",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="drip_campaign_config",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="drip_campaign_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
