# Generated by Django 5.0.1 on 2026-01-22 05:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contacts",
            "0003_contact_lead_score_activity_messagetemplate_segment_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="User this task is assigned to (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_app_task_reminders", models.BooleanField(default=True)),
                ("in_app_task_overdue", models.BooleanField(default=True)),
                ("in_app_task_assigned", models.BooleanField(default=True)),
                ("in_app_contact_activity", models.BooleanField(default=True)),
                ("in_app_workflow_completed", models.BooleanField(default=True)),
                ("in_app_system", models.BooleanField(default=True)),
                ("email_task_reminders", models.BooleanField(default=True)),
                ("email_task_overdue", models.BooleanField(default=True)),
                ("email_task_assigned", models.BooleanField(default=True)),
                ("email_daily_digest", models.BooleanField(default=False)),
                ("email_weekly_digest", models.BooleanField(default=False)),
                (
                    "daily_digest_time",
                    models.TimeField(
                        default=datetime.time(9, 0),
                        help_text="Time to send daily digest (UTC)",
                    ),
                ),
                (
                    "weekly_digest_day",
                    models.IntegerField(
                        default=1,
                        help_text="Day of week for weekly digest (0=Monday, 6=Sunday)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("task_reminder", "Task Reminder"),
                            ("task_overdue", "Task Overdue"),
                            ("task_assigned", "Task Assigned"),
                            ("contact_activity", "Contact Activity"),
                            ("workflow_completed", "Workflow Completed"),
                            ("system", "System"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="URL to navigate to when clicked",
                        max_length=500,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional notification data",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="contacts_no_user_id_c38b0e_idx",
                    )
                ],
            },
        ),
    ]
