# Generated by Django 5.0.1 on 2026-01-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_dripcampaign_dripcampaignstep"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="trial_end_at",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="trial_start_at",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("annual", "Annual")],
                default="monthly",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("canceled", "Canceled"),
                    ("incomplete", "Incomplete"),
                    ("incomplete_expired", "Incomplete Expired"),
                    ("unpaid", "Unpaid"),
                ],
                max_length=20,
            ),
        ),
    ]
