# Generated by Django 5.0.1 on 2025-12-15 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionFunnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("stage_1_name", models.CharField(default="Lead", max_length=100)),
                ("stage_1_count", models.IntegerField(default=0)),
                ("stage_2_name", models.CharField(default="Contacted", max_length=100)),
                ("stage_2_count", models.IntegerField(default=0)),
                ("stage_3_name", models.CharField(default="Qualified", max_length=100)),
                ("stage_3_count", models.IntegerField(default=0)),
                ("stage_4_name", models.CharField(default="Proposal", max_length=100)),
                ("stage_4_count", models.IntegerField(default=0)),
                ("stage_5_name", models.CharField(default="Won", max_length=100)),
                ("stage_5_count", models.IntegerField(default=0)),
                ("date_from", models.DateTimeField()),
                ("date_to", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion_funnels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=255)),
                ("total_leads", models.IntegerField(default=0)),
                ("qualified_leads", models.IntegerField(default=0)),
                ("converted_leads", models.IntegerField(default=0)),
                ("average_lead_score", models.FloatField(default=0)),
                ("conversion_rate", models.FloatField(default=0)),
                (
                    "average_time_to_conversion",
                    models.IntegerField(default=0, help_text="Average days to convert"),
                ),
                ("date_from", models.DateTimeField()),
                ("date_to", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-total_leads"],
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("total_contacts", models.IntegerField(default=0)),
                ("new_contacts", models.IntegerField(default=0)),
                ("active_contacts", models.IntegerField(default=0)),
                ("total_leads", models.IntegerField(default=0)),
                ("qualified_leads", models.IntegerField(default=0)),
                ("converted_leads", models.IntegerField(default=0)),
                ("emails_sent", models.IntegerField(default=0)),
                ("emails_opened", models.IntegerField(default=0)),
                ("emails_clicked", models.IntegerField(default=0)),
                ("calls_made", models.IntegerField(default=0)),
                ("meetings_held", models.IntegerField(default=0)),
                ("campaigns_active", models.IntegerField(default=0)),
                ("campaign_enrollments", models.IntegerField(default=0)),
                ("tasks_created", models.IntegerField(default=0)),
                ("tasks_completed", models.IntegerField(default=0)),
                ("tasks_overdue", models.IntegerField(default=0)),
                ("deals_won", models.IntegerField(default=0)),
                ("deals_lost", models.IntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
                "unique_together": {("owner", "period_type", "period_start")},
            },
        ),
    ]
