# Generated by Django 5.0.1 on 2025-12-12 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("welcome_email_enabled", models.BooleanField(default=True)),
                (
                    "welcome_email_template",
                    models.TextField(
                        default="Welcome to Ebookr! You're now part of our community.",
                        help_text="HTML template for welcome email",
                    ),
                ),
                ("trial_days", models.IntegerField(default=14)),
                ("enable_drip_campaigns", models.BooleanField(default=True)),
                ("enable_ai_features", models.BooleanField(default=False)),
                ("enable_reports", models.BooleanField(default=True)),
                ("rate_limit_requests_per_minute", models.IntegerField(default=60)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Admin Settings",
            },
        ),
        migrations.CreateModel(
            name="APIConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("sendgrid", "SendGrid"),
                            ("mailgun", "Mailgun"),
                            ("twilio", "Twilio"),
                            ("anthropic", "Anthropic (Claude)"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("api_key", models.TextField(help_text="Encrypted API key")),
                (
                    "api_secret",
                    models.TextField(blank=True, help_text="Optional API secret"),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True, help_text="Webhook URL for this service"
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["service"],
            },
        ),
        migrations.CreateModel(
            name="EmailConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("sendgrid", "SendGrid"),
                            ("mailgun", "Mailgun"),
                            ("smtp", "SMTP"),
                        ],
                        default="sendgrid",
                        max_length=50,
                    ),
                ),
                ("from_email", models.EmailField(max_length=254)),
                ("from_name", models.CharField(default="Ebookr", max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("smtp_host", models.CharField(blank=True, max_length=255)),
                ("smtp_port", models.IntegerField(blank=True, null=True)),
                ("smtp_username", models.CharField(blank=True, max_length=255)),
                ("smtp_password", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Email Configurations",
            },
        ),
        migrations.CreateModel(
            name="AdminSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "tier",
                    models.CharField(
                        choices=[("starter", "Starter"), ("pro", "Pro")],
                        default="starter",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signup_record",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
