# Generated by Django 5.0.1 on 2026-01-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_alter_adminsignup_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminsettings",
            name="trial_days",
        ),
        migrations.AlterField(
            model_name="adminsettings",
            name="enable_ai_features",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="adminsignup",
            name="tier",
            field=models.CharField(
                choices=[("pro", "Pro")], default="pro", max_length=50
            ),
        ),
    ]
