# Generated by Django 5.0.1 on 2025-12-15 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("email", "Email Service"),
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS Service"),
                            ("signup_page", "Sign Up Page"),
                            ("facebook", "Facebook"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this integration", max_length=255
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Service provider (e.g., SendGrid, Twilio, Mailchimp)",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                            ("pending", "Pending Setup"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Integration-specific configuration"
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("owner", "integration_type", "provider")},
            },
        ),
        migrations.CreateModel(
            name="FacebookIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.CharField(max_length=255)),
                ("app_secret", models.CharField(max_length=500)),
                ("access_token", models.CharField(max_length=500)),
                ("page_id", models.CharField(blank=True, max_length=255)),
                ("page_access_token", models.CharField(blank=True, max_length=500)),
                ("enable_lead_ads", models.BooleanField(default=False)),
                ("lead_form_id", models.CharField(blank=True, max_length=255)),
                ("enable_messenger", models.BooleanField(default=False)),
                ("webhook_verify_token", models.CharField(blank=True, max_length=500)),
                ("webhook_url", models.URLField(blank=True)),
                ("auto_create_contact_from_leads", models.BooleanField(default=True)),
                (
                    "trigger_campaign_on_lead",
                    models.IntegerField(
                        blank=True,
                        help_text="Campaign to trigger when lead is captured",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facebook_config",
                        to="integrations.integration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("sendgrid", "SendGrid"),
                            ("mailgun", "Mailgun"),
                            ("aws_ses", "AWS SES"),
                            ("smtp", "SMTP"),
                            ("mailchimp", "Mailchimp"),
                        ],
                        max_length=50,
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=500)),
                ("from_email", models.EmailField(max_length=254)),
                ("from_name", models.CharField(blank=True, max_length=255)),
                ("reply_to_email", models.EmailField(blank=True, max_length=254)),
                ("smtp_host", models.CharField(blank=True, max_length=255)),
                ("smtp_port", models.IntegerField(blank=True, null=True)),
                ("smtp_username", models.CharField(blank=True, max_length=255)),
                ("smtp_password", models.CharField(blank=True, max_length=500)),
                ("smtp_use_tls", models.BooleanField(default=True)),
                ("aws_region", models.CharField(blank=True, max_length=50)),
                ("aws_access_key_id", models.CharField(blank=True, max_length=255)),
                ("aws_secret_access_key", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_config",
                        to="integrations.integration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="integrations.integration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SignUpPageIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_url", models.URLField(blank=True)),
                (
                    "embed_code",
                    models.TextField(
                        blank=True, help_text="HTML embed code for the sign-up form"
                    ),
                ),
                (
                    "api_endpoint",
                    models.URLField(
                        blank=True, help_text="API endpoint to receive sign-ups"
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=500)),
                (
                    "form_fields",
                    models.JSONField(
                        default=list, help_text="List of form fields to collect"
                    ),
                ),
                (
                    "redirect_url",
                    models.URLField(
                        blank=True, help_text="URL to redirect after successful sign-up"
                    ),
                ),
                (
                    "auto_create_contact",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create contact on sign-up",
                    ),
                ),
                (
                    "apply_tag",
                    models.CharField(
                        blank=True,
                        help_text="Tag to apply to new contacts",
                        max_length=100,
                    ),
                ),
                (
                    "trigger_campaign_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Campaign to trigger on sign-up",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signup_config",
                        to="integrations.integration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SMSIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("twilio", "Twilio"),
                            ("vonage", "Vonage (Nexmo)"),
                            ("aws_sns", "AWS SNS"),
                            ("plivo", "Plivo"),
                        ],
                        max_length=50,
                    ),
                ),
                ("account_sid", models.CharField(blank=True, max_length=255)),
                ("auth_token", models.CharField(max_length=500)),
                ("api_key", models.CharField(blank=True, max_length=500)),
                ("api_secret", models.CharField(blank=True, max_length=500)),
                ("from_phone_number", models.CharField(max_length=20)),
                ("aws_region", models.CharField(blank=True, max_length=50)),
                ("aws_access_key_id", models.CharField(blank=True, max_length=255)),
                ("aws_secret_access_key", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_config",
                        to="integrations.integration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WhatsAppIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number_id", models.CharField(max_length=255)),
                ("business_account_id", models.CharField(max_length=255)),
                ("access_token", models.CharField(max_length=500)),
                ("webhook_verify_token", models.CharField(blank=True, max_length=500)),
                ("webhook_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_config",
                        to="integrations.integration",
                    ),
                ),
            ],
        ),
    ]
