# Generated by Django 5.0.1 on 2026-01-22 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "automation",
            "0002_workflow_abtest_workflowcondition_workflowtemplate_and_more",
        ),
        (
            "contacts",
            "0003_contact_lead_score_activity_messagetemplate_segment_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledTaskBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_name", models.CharField(max_length=255)),
                (
                    "batch_type",
                    models.CharField(
                        help_text="follow_up_sequence, recurring, automation_workflow, etc.",
                        max_length=50,
                    ),
                ),
                ("tasks_count", models.IntegerField(default=0)),
                ("tasks_completed", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_batches",
                        to="contacts.contact",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_task_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Scheduled task batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskAutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("activity", "Activity Trigger"),
                            ("status_change", "Status Change"),
                            ("new_contact", "New Contact"),
                            ("cadence", "Contact Cadence"),
                            ("overdue_followup", "Overdue Follow-up"),
                            ("time_based", "Time-based"),
                        ],
                        max_length=50,
                    ),
                ),
                ("trigger_config", models.JSONField(default=dict)),
                (
                    "task_title_template",
                    models.CharField(
                        help_text="Use {{contact_name}}, {{activity_type}}, etc.",
                        max_length=255,
                    ),
                ),
                ("task_description_template", models.TextField(blank=True)),
                (
                    "task_priority",
                    models.CharField(
                        default="medium",
                        help_text="low, medium, high, urgent",
                        max_length=20,
                    ),
                ),
                (
                    "delay_hours",
                    models.IntegerField(
                        default=24, help_text="Hours after trigger to schedule task"
                    ),
                ),
                (
                    "reminder_offset_hours",
                    models.IntegerField(
                        default=1, help_text="Hours before due date to set reminder"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("times_triggered", models.IntegerField(default=0)),
                ("tasks_created", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_automation_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
