# Generated by Django 5.0.1 on 2025-12-15 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "contacts",
            "0003_contact_lead_score_activity_messagetemplate_segment_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google_calendar", "Google Calendar"),
                            ("outlook_calendar", "Outlook Calendar"),
                            ("salesforce", "Salesforce"),
                            ("hubspot", "HubSpot"),
                            ("pipedrive", "Pipedrive"),
                            ("zoho", "Zoho CRM"),
                            ("zapier", "Zapier"),
                            ("make", "Make"),
                            ("slack", "Slack"),
                            ("custom", "Custom Webhook"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Custom name for this integration", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                            ("pending", "Pending Authorization"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("api_key", models.CharField(blank=True, max_length=500)),
                ("api_secret", models.CharField(blank=True, max_length=500)),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Provider-specific configuration"
                    ),
                ),
                ("webhook_url", models.URLField(blank=True, max_length=500)),
                ("sync_enabled", models.BooleanField(default=True)),
                ("sync_interval_minutes", models.PositiveIntegerField(default=15)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("next_sync_at", models.DateTimeField(blank=True, null=True)),
                ("total_syncs", models.PositiveIntegerField(default=0)),
                ("failed_syncs", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_field", models.CharField(max_length=200)),
                (
                    "source_field_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("datetime", "DateTime"),
                            ("json", "JSON"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        help_text="contacts.Contact, etc.", max_length=100
                    ),
                ),
                ("target_field", models.CharField(max_length=200)),
                (
                    "transform_function",
                    models.CharField(
                        blank=True,
                        help_text="Optional transformation function",
                        max_length=100,
                    ),
                ),
                ("default_value", models.CharField(blank=True, max_length=500)),
                ("is_required", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="crm_integrations.integration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalendarSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_event_id", models.CharField(max_length=500, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("timezone", models.CharField(default="UTC", max_length=100)),
                ("location", models.CharField(blank=True, max_length=500)),
                ("meeting_url", models.URLField(blank=True, max_length=500)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting"),
                            ("call", "Call"),
                            ("follow_up", "Follow Up"),
                            ("demo", "Demo"),
                            ("other", "Other"),
                        ],
                        default="meeting",
                        max_length=50,
                    ),
                ),
                (
                    "attendees",
                    models.JSONField(default=list, help_text="List of attendee emails"),
                ),
                ("is_synced", models.BooleanField(default=False)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_errors", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_contacts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="calendar_events",
                        to="contacts.contact",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="crm_integrations.integration",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound"),
                            ("outbound", "Outbound"),
                            ("bidirectional", "Bidirectional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("records_processed", models.PositiveIntegerField(default=0)),
                ("records_created", models.PositiveIntegerField(default=0)),
                ("records_updated", models.PositiveIntegerField(default=0)),
                ("records_failed", models.PositiveIntegerField(default=0)),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        help_text="Sync duration in milliseconds"
                    ),
                ),
                ("error_messages", models.JSONField(default=list)),
                ("details", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="crm_integrations.integration",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField(max_length=500)),
                (
                    "events",
                    models.JSONField(
                        default=list, help_text="List of events to trigger webhook"
                    ),
                ),
                ("secret", models.CharField(max_length=100, unique=True)),
                (
                    "headers",
                    models.JSONField(
                        default=dict, help_text="Custom headers to include"
                    ),
                ),
                (
                    "payload_template",
                    models.TextField(
                        blank=True, help_text="Optional custom payload template"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("total_calls", models.PositiveIntegerField(default=0)),
                ("failed_calls", models.PositiveIntegerField(default=0)),
                ("last_called_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status_code",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("is_success", models.BooleanField(default=False)),
                (
                    "duration_ms",
                    models.PositiveIntegerField(help_text="Request duration"),
                ),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="crm_integrations.webhook",
                    ),
                ),
            ],
            options={
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("key", models.CharField(max_length=100, unique=True)),
                (
                    "scopes",
                    models.JSONField(default=list, help_text="API scopes/permissions"),
                ),
                ("rate_limit_per_hour", models.PositiveIntegerField(default=1000)),
                (
                    "allowed_ips",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Whitelist of allowed IP addresses",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("total_requests", models.PositiveBigIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["key", "is_active"], name="crm_integra_key_ffa54d_idx"
                    ),
                    models.Index(
                        fields=["owner", "is_active"],
                        name="crm_integra_owner_i_49d4dc_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="integration",
            index=models.Index(
                fields=["owner", "provider", "status"],
                name="crm_integra_owner_i_c38945_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integration",
            index=models.Index(
                fields=["next_sync_at"], name="crm_integra_next_sy_0106af_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="integration",
            unique_together={("owner", "provider", "name")},
        ),
        migrations.AddIndex(
            model_name="datamapping",
            index=models.Index(
                fields=["integration", "is_active"],
                name="crm_integra_integra_0c99c2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="datamapping",
            unique_together={
                ("integration", "source_field", "target_model", "target_field")
            },
        ),
        migrations.AddIndex(
            model_name="calendarsync",
            index=models.Index(
                fields=["owner", "start_time"], name="crm_integra_owner_i_cba62c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarsync",
            index=models.Index(
                fields=["external_event_id"], name="crm_integra_externa_d59ed3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["integration", "-started_at"],
                name="crm_integra_integra_6173b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(fields=["status"], name="crm_integra_status_13b731_idx"),
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(
                fields=["owner", "is_active"], name="crm_integra_owner_i_dfae1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhooklog",
            index=models.Index(
                fields=["webhook", "-attempted_at"],
                name="crm_integra_webhook_25828f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhooklog",
            index=models.Index(
                fields=["is_success"], name="crm_integra_is_succ_0b78cc_idx"
            ),
        ),
    ]
