# Generated by Django 5.0.1 on 2025-12-15 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "contacts",
            "0003_contact_lead_score_activity_messagetemplate_segment_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIEmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("introduction", "Introduction"),
                            ("follow_up", "Follow Up"),
                            ("proposal", "Proposal"),
                            ("thank_you", "Thank You"),
                            ("re_engagement", "Re-engagement"),
                            ("meeting_request", "Meeting Request"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="AI prompt template for generating email content"
                    ),
                ),
                ("subject_template", models.CharField(blank=True, max_length=500)),
                ("body_template", models.TextField(blank=True)),
                (
                    "tone",
                    models.CharField(
                        default="professional",
                        help_text="professional, friendly, casual, formal",
                        max_length=50,
                    ),
                ),
                (
                    "personalization_fields",
                    models.JSONField(
                        default=dict, help_text="Fields to use for personalization"
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "success_rate",
                    models.FloatField(
                        default=0.0, help_text="Response rate percentage"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_email_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engagement_score", models.FloatField(default=0.0)),
                ("recency_score", models.FloatField(default=0.0)),
                ("response_rate_score", models.FloatField(default=0.0)),
                ("profile_completeness", models.FloatField(default=0.0)),
                ("overall_score", models.FloatField(default=0.0)),
                (
                    "score_level",
                    models.CharField(
                        choices=[
                            ("hot", "Hot Lead"),
                            ("warm", "Warm Lead"),
                            ("cold", "Cold Lead"),
                            ("nurture", "Needs Nurturing"),
                            ("inactive", "Inactive"),
                        ],
                        default="cold",
                        max_length=20,
                    ),
                ),
                ("conversion_probability", models.FloatField(default=0.0)),
                ("churn_risk", models.FloatField(default=0.0)),
                ("next_best_action", models.CharField(blank=True, max_length=200)),
                ("key_insights", models.JSONField(default=list)),
                ("behavioral_patterns", models.JSONField(default=dict)),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_score",
                        to="contacts.contact",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-overall_score"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_used", models.TextField()),
                ("subject", models.CharField(max_length=500)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("opened", "Opened"),
                            ("replied", "Replied"),
                            ("bounced", "Bounced"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("engagement_score", models.FloatField(blank=True, null=True)),
                (
                    "ai_model_used",
                    models.CharField(default="claude-3-5-sonnet", max_length=100),
                ),
                (
                    "generation_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_emails",
                        to="contacts.contact",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_emails",
                        to="ai_features.aiemailtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PredictiveAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("contact_growth", "Contact Growth"),
                            ("conversion_rate", "Conversion Rate"),
                            ("email_engagement", "Email Engagement"),
                            ("deal_closure", "Deal Closure"),
                            ("churn_rate", "Churn Rate"),
                        ],
                        max_length=50,
                    ),
                ),
                ("historical_data", models.JSONField()),
                ("training_period_days", models.PositiveIntegerField(default=90)),
                ("predicted_values", models.JSONField()),
                ("forecast_period_days", models.PositiveIntegerField(default=30)),
                ("confidence_interval", models.JSONField()),
                ("accuracy_score", models.FloatField(blank=True, null=True)),
                (
                    "trend_direction",
                    models.CharField(
                        choices=[
                            ("up", "Increasing"),
                            ("down", "Decreasing"),
                            ("stable", "Stable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("anomalies_detected", models.JSONField(default=list)),
                ("recommendations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Predictive analytics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SentimentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("note", "Note"),
                            ("call", "Call"),
                        ],
                        max_length=50,
                    ),
                ),
                ("source_text", models.TextField()),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("very_positive", "Very Positive"),
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                            ("very_negative", "Very Negative"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sentiment_score", models.FloatField()),
                ("confidence", models.FloatField()),
                ("emotions", models.JSONField(default=dict)),
                ("key_phrases", models.JSONField(default=list)),
                (
                    "response_urgency",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent"),
                            ("moderate", "Moderate"),
                            ("low", "Low"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment_analyses",
                        to="contacts.contact",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sentiment analyses",
                "ordering": ["-analyzed_at"],
            },
        ),
        migrations.CreateModel(
            name="SmartRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("contact_action", "Contact Action"),
                            ("workflow_suggestion", "Workflow Suggestion"),
                            ("template_usage", "Template Usage"),
                            ("timing_optimization", "Timing Optimization"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("context_data", models.JSONField(default=dict)),
                ("expected_impact", models.TextField(blank=True)),
                ("confidence_score", models.FloatField(default=0.5)),
                ("is_viewed", models.BooleanField(default=False)),
                ("is_acted_upon", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-confidence_score", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aiemailtemplate",
            index=models.Index(
                fields=["owner", "category"], name="ai_features_owner_i_f57a8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiemailtemplate",
            index=models.Index(
                fields=["is_active", "-usage_count"],
                name="ai_features_is_acti_f91e44_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contactscore",
            index=models.Index(
                fields=["owner", "-overall_score"],
                name="ai_features_owner_i_7b1683_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contactscore",
            index=models.Index(
                fields=["score_level"], name="ai_features_score_l_816e39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedemail",
            index=models.Index(
                fields=["owner", "status"], name="ai_features_owner_i_b8fd3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedemail",
            index=models.Index(
                fields=["contact", "-created_at"], name="ai_features_contact_a941d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smartrecommendation",
            index=models.Index(
                fields=["owner", "is_dismissed", "expires_at"],
                name="ai_features_owner_i_646244_idx",
            ),
        ),
    ]
